name: get-started-suite

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e-pr-blocking:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run get-started test
      run: echo Y | ./hack/getting_started.sh --cni

